### ISSUE TITLE
HTML 

### ISSUE THREAD

**Issue by anaorozco96** [anaorozco96/prework-study-guide#1]
# HTML 

## User Story
As a bootcamp student 
I want the prework notes to be structured on a webpage
so that i can easily find and read information 

## Acceptance Criteria 
GIVEN a Prework Study Guide website 
WHEN I visit the website in my browser
THEN I seen four boxes titled HTML, CSS,Git, and JavaScript with associated notes listed

**Comment by lewisad97** [comment]
Hello! I have recently been learning bootstrap and have discovered a feature which is quick to implement into your main HTML.
A responsive navbar with a dropdown menu- This will enable you to categorise your study material in the dropdown menu for easy access without cramming all your content onto one page.

**Comment by anaorozco96** [comment]
Thank you ! i will definitely try it out. i am berly getting familiar with
Git Hub 😅

**Comment by lewisad97** [comment]
No worries if you create your initial HTML and upload it to GitHub I can implement the changes so you can see if you want to commit them? If not it might give you an idea and allow you to play about with it.
